library(tidyverse)
library(dslabs)
library(dplyr)

data(gapminder)
library(readxl)
path <- system.file("extdata", package="dslabs")
filename <- file.path(path,  "fertility-two-countries-example.csv")
wide_data <- read_csv(filename)
select(wide_data, country, `1960`:`1967`)
